name: countcorrect
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.7
  - cxx-compiler
  - blas-devel
  - mkl-service
  - numpy
  - theano
  - tensorflow
  - blas
  - pymc3>=3.8,<3.10
  - pandas<1.3
  - h5py<3.2
  - jupyter
  - scanpy
  - ipython
  - seaborn
  - matplotlib
  - pygpu
  - anndata
  - click
  - pip
  - pip:
    - diffxpy
    - torch
    - arviz==0.11.1
    - adjustText
    - git+https://github.com/BayraktarLab/CountCorrect/
