name: countcorrect
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.7
  - clangxx_osx-64
  - mkl-service
  - libcxx
  - numpy
  - pandas<1.3
  - h5py<3.2
  - jupyter
  - scanpy
  - ipython
  - seaborn
  - matplotlib
  - pygpu
  - anndata
  - click
  - pip
  - pip:
    - pymc3>=3.8,<3.10
    - diffxpy
    - torch
    - arviz==0.11.1
    - adjustText
    - git+https://github.com/BayraktarLab/CountCorrect/
