name: countcorrect
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.12
  - anndata=0.7.5
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bleach=3.3.0
  - blosc=1.21.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cached-property=1.5.1
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - colorama=0.4.4
  - cryptography=3.4.4
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - docutils=0.16
  - entrypoints=0.3
  - expat=2.2.10
  - fontconfig=2.13.1
  - freetype=2.10.4
  - get_version=2.1
  - gettext=0.19.8.1
  - glib=2.66.7
  - glib-tools=2.66.7
  - gst-plugins-base=1.18.3
  - gstreamer=1.18.3
  - h5py=3.1.0
  - hdf5=1.10.6
  - icu=68.1
  - idna=2.10
  - imagesize=1.2.0
  - importlib-metadata=3.6.0
  - importlib_metadata=3.6.0
  - ipykernel=5.5.0
  - ipython=7.20.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=2.11.3
  - joblib=1.0.1
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.11
  - jupyter_console=6.2.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - legacy-api-wrap=1.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.0.1
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.7
  - libgomp=9.3.0
  - libgpuarray=0.7.6
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libllvm11=11.0.1
  - libnghttp2=1.43.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libpq=13.1
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.10
  - llvmlite=0.35.0
  - lz4-c=1.9.3
  - lzo=2.10
  - mako=1.1.4
  - markupsafe=1.1.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mistune=0.8.4
  - mock=4.0.3
  - mysql-common=8.0.23
  - mysql-libs=8.0.23
  - natsort=7.1.1
  - nbclient=0.5.2
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - networkx=2.5
  - notebook=6.2.0
  - nspr=4.29
  - nss=3.62
  - numba=0.52.0
  - numexpr=2.7.2
  - numpy=1.20.1
  - olefile=0.46
  - openssl=1.1.1j
  - packaging=20.9
  - pandas=1.2.2
  - pandoc=2.11.4
  - pandocfilters=1.4.2
  - parso=0.8.1
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pip=21.0.1
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.16
  - prompt_toolkit=3.0.16
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.8.0
  - pygpu=0.7.6
  - pynndescent=0.5.2
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytables=3.6.1
  - python=3.7.10
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2021.1
  - pyzmq=22.0.3
  - qt=5.12.9
  - qtconsole=5.0.2
  - qtpy=1.9.0
  - readline=8.0
  - requests=2.25.1
  - scanpy=1.7.0
  - scikit-learn=0.24.1
  - scipy=1.6.0
  - seaborn=0.11.1
  - seaborn-base=0.11.1
  - send2trash=1.5.0
  - setuptools=49.6.0
  - setuptools-scm=5.0.1
  - setuptools_scm=5.0.1
  - sinfo=0.3.1
  - six=1.15.0
  - snowballstemmer=2.1.0
  - sphinx=3.5.1
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.34.0
  - statsmodels=0.12.2
  - stdlib-list=0.7.0
  - tbb=2020.2
  - terminado=0.9.2
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.57.0
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - umap-learn=0.5.1
  - urllib3=1.26.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.8
